export const cityTimezoneMap = {
  // north America
  ' New York': 'America/New_York',
  'Los Angeles': 'America/Los_Angeles',
  Chicago: 'America/Chicago',
  Houston: 'America/Chicago',
  Miami: 'America/New_York',
  'San Francisco': 'America/Los_Angeles',
  Boston: 'America/New_York',
  Dallas: 'America/Chicago',
  Atlanta: 'America/New_York',
  Seattle: 'America/Los_Angeles',
  Denver: 'America/Denver',
  Philadelphia: 'America/New_York',
  Phoenix: 'America/Phoenix',
  'Las Vegas': 'America/Los_Angeles',
  'San Diego': 'America/Los_Angeles',
  Orlando: 'America/New_York',
  'Washington, D.C.': 'America/New_York',
  Austin: 'America/Chicago',
  'San Antonio': 'America/Chicago',
  Nashville: 'America/Chicago',
  Toronto: 'America/Toronto',
  Vancouver: 'America/Vancouver',
  Montreal: 'America/Toronto',
  Calgary: 'America/Edmonton',
  Edmonton: 'America/Edmonton',
  Ottawa: 'America/Toronto',
  Winnipeg: 'America/Winnipeg',
  Halifax: 'America/Halifax',
  'Quebec City': 'America/Toronto',
  Victoria: 'America/Vancouver',
  'Mexico City': 'America/Mexico_City',
  Guadalajara: 'America/Mexico_City',
  Monterrey: 'America/Monterrey',
  Puebla: 'America/Mexico_City',
  Tijuana: 'America/Tijuana',
  Mérida: 'America/Merida',
  Cancún: 'America/Cancun',
  León: 'America/Mexico_City',
  Chihuahua: 'America/Chihuahua',
  Toluca: 'America/Mexico_City',
  'Havana (Cuba)': 'America/Havana',
  'Santo Domingo': 'America/Santo_Domingo',
  'Kingston (Jamaica)': 'America/Jamaica',
  'Port-au-PrinceAmerica/Port-': 'au-Prince',
  'Nassau (Bahamas)': 'America/Nassau',
  'San Juan (Puerto Rico)': 'America/Puerto_Rico',
  // asia
  Tokyo: 'Asia/Tokyo',
  Shanghai: 'Asia/Shanghai',
  Beijing: 'Asia/Shanghai',
  Seoul: 'Asia/Seoul',
  'Hong Kong': 'Asia/Hong_Kong',
  Taipei: 'Asia/Taipei',
  Guangzhou: 'Asia/Shanghai',
  Shenzhen: 'Asia/Shanghai',
  Bangkok: 'Asia/Bangkok',
  'Kuala Lumpur': 'Asia/Kuala_Lumpur',
  Mumbai: 'Asia/Kolkata',
  Delhi: 'Asia/Kolkata',
  Karachi: 'Asia/Karachi',
  Bengaluru: 'Asia/Kolkata',
  Dhaka: 'Asia/Dhaka',
  Chennai: 'Asia/Kolkata',
  Lahore: 'Asia/Karachi',
  Islamabad: 'Asia/Karachi',
  Kathmandu: 'Asia/Kathmandu',
  Colombo: 'Asia/Colombo',
  'Ho Chi Minh City': 'Asia/Ho_Chi_Minh',
  Hanoi: 'Asia/Ho_Chi_Minh',
  Manila: 'Asia/Manila',
  Singapore: 'Asia/Singapore',
  Jakarta: 'Asia/Jakarta',
  Riyadh: 'Asia/Riyadh',
  Dubai: 'Asia/Dubai',
  Tehran: 'Asia/Tehran',
  Jeddah: 'Asia/Riyadh',
  Beirut: 'Asia/Beirut',
  Doha: 'Asia/Qatar',
  Manama: 'Asia/Bahrain',
  Amman: 'Asia/Amman',
  Muscat: 'Asia/Muscat',
  Almaty: 'Asia/Almaty',
  Tashkent: 'Asia/Tashkent',
  Bishkek: 'Asia/Bishkek',
  Ashgabat: 'Asia/Ashgabat',
  Dushanbe: 'Asia/Dushanbe',
  'Nur-Sultan': 'Asia/Almaty',
  Ulaanbaatar: 'Asia/Ulaanbaatar',
  Astana: 'Asia/Almaty',
  Baku: 'Asia/Baku',
  Tbilisi: 'Asia/Tbilisi',
  Male: 'Indian/Maldives',
  Thimphu: 'Asia/Thimphu',
  Srinagar: 'Asia/Kolkata',
  Kabul: 'Asia/Kabul',
  Malegaon: 'Asia/Kolkata',
  Jaipur: 'Asia/Kolkata',
  Chengdu: 'Asia/Shanghai',
  Chongqing: 'Asia/Shanghai',
  Tianjin: 'Asia/Shanghai',
  Wuhan: 'Asia/Shanghai',
  Hangzhou: 'Asia/Shanghai',
  "Xi'an": 'Asia/Shanghai',
  Nanjing: 'Asia/Shanghai',
  Shenyang: 'Asia/Shanghai',
  Harbin: 'Asia/Shanghai',
  Suzhou: 'Asia/Shanghai',
  Qingdao: 'Asia/Shanghai',
  Dalian: 'Asia/Shanghai',
  Zhengzhou: 'Asia/Shanghai',
  Changsha: 'Asia/Shanghai',
  Kunming: 'Asia/Shanghai',
  Fuzhou: 'Asia/Shanghai',
  // south America,
  'São Paulo': 'America":"Sao_Paulo',
  'Buenos Aires	America': 'Argentina/Buenos_Aires',
  'Rio de Janeiro': 'America/Sao_Paulo',
  Lima: 'America/Lima',
  Bogotá: 'America/Bogota',
  Santiago: 'America/Santiago',
  Caracas: 'America/Caracas',
  Quito: 'America/Guayaquil',
  Montevideo: 'America/Montevideo',
  Asunción: 'America/Asuncion',
  'La Paz': 'America/La_Paz',
  Guayaquil: 'America/Guayaquil',
  Recife: 'America/Recife',
  Salvador: 'America/Bahia',
  Medellín: 'America/Bogota',
  Curitiba: 'America/Sao_Paulo',
  Fortaleza: 'America/Fortaleza',
  'Belo Horizonte': 'America/Sao_Paulo',

  // africa
  Cairo: 'Africa/Cairo',
  Johannesburg: 'Africa/Johannesburg',
  Lagos: 'Africa/Lagos',
  Nairobi: 'Africa/Nairobi',
  Casablanca: 'Africa/Casablanca',

  // Oceania
  Sydney: 'Australia/Sydney',
  Melbourne: 'Australia/Melbourne',
  Brisbane: 'Australia/Brisbane',
  Perth: 'Australia/Perth',
  Adelaide: 'Australia/Adelaide',
  Canberra: 'Australia/Sydney',
  Hobart: 'Australia/Hobart',
  Darwin: 'Australia/Darwin',
  'Gold Coast': 'Australia/Brisbane',
  Newcastle: 'Australia/Sydney',
  Cairns: 'Australia/Brisbane',
  Wollongong: 'Australia/Sydney',
  Townsville: 'Australia/Brisbane',
  Geelong: 'Australia/Melbourne',
  Auckland: 'Pacific/Auckland',
  Wellington: 'Pacific/Wellington',
  Suva: 'Pacific/Fiji',
  'Port Moresby': 'Pacific/Port_Moresby',
  Nouméa: 'Pacific/Noumea',
  Apia: 'Pacific/Apia',
  "Nuku'alofa": 'Pacific/Tongatapu',
  Honiara: 'Pacific/Guadalcanal',
  Funafuti: 'Pacific/Funafuti',
  Tarawa: 'Pacific/Kiritimati',
  Papeete: 'Pacific/Tahiti',

  // Europe
  London: 'Europe/London',
  Paris: 'Europe/Paris',
  Madrid: 'Europe/Madrid',
  Berlin: 'Europe/Berlin',
  Amsterdam: 'Europe/Amsterdam',
  Brussels: 'Europe/Brussels',
  Lisbon: 'Europe/Lisbon',
  Zurich: 'Europe/Zurich',
  Vienna: 'Europe/Vienna',
  Dublin: 'Europe/Dublin',
  Rome: 'Europe/Rome',
  Athens: 'Europe/Athens',
  Moscow: 'Europe/Moscow',
  Istanbul: 'Europe/Istanbul',
  Warsaw: 'Europe/Warsaw',
  Prague: 'Europe/Prague',
  Budapest: 'Europe/Budapest',
  Bucharest: 'Europe/Bucharest',
  Sofia: 'Europe/Sofia',
  Belgrade: 'Europe/Belgrade',
  Kyiv: 'Europe/Kiev',
  Minsk: 'Europe/Minsk',
  Stockholm: 'Europe/Stockholm',
  Helsinki: 'Europe/Helsinki',
  Copenhagen: 'Europe/Copenhagen',
  Oslo: 'Europe/Oslo',
  Reykjavik: 'Atlantic/Reykjavik',
  Edinburgh: 'Europe/London',
  Glasgow: 'Europe/London',
  Manchester: 'Europe/London',
  Birmingham: 'Europe/London',
  Liverpool: 'Europe/London',
  Naples: 'Europe/Rome',
  Marseille: 'Europe/Paris',
  Genoa: 'Europe/Rome',
  Palermo: 'Europe/Rome',
  Malta: 'Europe/Malta',
  Valletta: 'Europe/Malta',
  Tunis: 'Africa/Tunis',
};
